#!/usr/bin/env python3
"""Generate resources/THIRD_PARTY_LICENSES.txt from `cargo metadata`.

Covers every crate that can end up in a shipped binary: all target platforms,
all features, normal + build dependencies (dev-dependencies excluded). License
texts are copied verbatim from each crate's source and deduplicated by content.

Usage:
    python3 scripts/generate-third-party-licenses.py          # rewrite the file
    python3 scripts/generate-third-party-licenses.py --check  # CI: fail if stale
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "resources" / "THIRD_PARTY_LICENSES.txt"
LICENSE_FILE_RE = re.compile(r"^(LICEN[CS]E|COPYING|NOTICE|UNLICENSE)", re.IGNORECASE)
SEPARATOR = "=" * 78

HEADER = """\
MistTerm — Third-Party Software Notices
=======================================

MistTerm is licensed under the GNU Affero General Public License v3.0 or later.
Source code: https://github.com/mistlab-dev/MistTerm

MistTerm includes the third-party open-source components listed below. Each
component remains under its own license; the full license texts follow.

This file is generated by scripts/generate-third-party-licenses.py.
Do not edit it by hand.
"""


def cargo_metadata() -> dict:
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked", "--all-features"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return json.loads(out)


def shipped_packages(meta: dict) -> list[dict]:
    packages = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    members = set(meta["workspace_members"])
    seen: set[str] = set()
    stack = list(members)
    while stack:
        node_id = stack.pop()
        if node_id in seen:
            continue
        seen.add(node_id)
        for dep in nodes[node_id]["deps"]:
            kinds = {k["kind"] for k in dep["dep_kinds"]}
            if kinds - {"dev"}:
                stack.append(dep["pkg"])
    return sorted(
        (packages[i] for i in seen - members),
        key=lambda p: (p["name"], p["version"]),
    )


def normalize(text: str) -> str:
    lines = [line.rstrip() for line in text.replace("\r\n", "\n").split("\n")]
    return "\n".join(lines).strip("\n")


def license_texts(pkg: dict) -> list[str]:
    pkg_dir = pathlib.Path(pkg["manifest_path"]).parent
    candidates: list[pathlib.Path] = []
    if pkg.get("license_file"):
        candidates.append(pkg_dir / pkg["license_file"])
    candidates += sorted(
        f for f in pkg_dir.iterdir() if f.is_file() and LICENSE_FILE_RE.match(f.name)
    )
    texts: list[str] = []
    seen_paths: set[pathlib.Path] = set()
    for path in candidates:
        resolved = path.resolve()
        if resolved in seen_paths or not resolved.is_file():
            continue
        seen_paths.add(resolved)
        text = normalize(resolved.read_text(encoding="utf-8", errors="replace"))
        if text and text not in texts:
            texts.append(text)
    return texts


def crate_label(pkg: dict) -> str:
    return f"{pkg['name']} {pkg['version']}"


def render(packages: list[dict]) -> str:
    groups: dict[str, list[str]] = {}
    without_file: list[dict] = []
    for pkg in packages:
        texts = license_texts(pkg)
        if not texts:
            without_file.append(pkg)
        for text in texts:
            groups.setdefault(text, []).append(crate_label(pkg))

    out = [HEADER, "", "Components", "----------", ""]
    width = max(len(crate_label(p)) for p in packages)
    for pkg in packages:
        spdx = pkg.get("license") or "see license file"
        out.append(f"  {crate_label(pkg).ljust(width)}  {spdx}")

    if without_file:
        out += [
            "",
            "The following components declare their license by SPDX identifier only",
            "and ship no license file; the standard text of that license applies",
            "(https://spdx.org/licenses/):",
            "",
        ]
        out += [f"  {crate_label(p)}  {p.get('license')}" for p in without_file]

    for text, crates in sorted(groups.items(), key=lambda kv: (kv[1][0], kv[0])):
        out += ["", SEPARATOR, "Applies to: " + ", ".join(crates), SEPARATOR, "", text]
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args()

    packages = shipped_packages(cargo_metadata())
    content = render(packages)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print(
                f"{OUT.relative_to(ROOT)} is out of date; run "
                "`python3 scripts/generate-third-party-licenses.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date.")
        return 0

    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(packages)} components, {len(content) // 1024} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
